import { assertEquals, assertStringIncludes } from "@std/assert";
import { join } from "@std/path";
import ts from "typescript";
import { globalsDts, jsconfig } from "../fileConstants.ts";
import { createClient } from "../src/client.ts";
import { fetchDocs, parseDocs } from "../src/typegen/docs.ts";
import { emitDeclarations, hintText, paramList } from "../src/typegen/emit.ts";
import { DOCS_FIXTURES, FakeServer, SERVER_URL } from "./helpers.ts";

const docs = () =>
  parseDocs(SERVER_URL, {
    indexHtml: DOCS_FIXTURES["index.html"],
    classesJs: DOCS_FIXTURES["json/classes.js"],
    symbolsJs: DOCS_FIXTURES["json/symbols.js"],
  });

Deno.test("reads symbols, classes and plugin globals from the docs files", () => {
  const d = docs();
  assertEquals(d.version, "1.2.3");
  assertEquals(d.symbols.map((s) => s.symbol).includes("PayloadHelper"), true);
  assertEquals(
    d.classes.find((c) => c.className === "code.data.generic.ApiRequest")
      ?.aliases,
    ["ApiRequest", "generic_ApiRequest"],
  );
  // Only the plugin additions inlined in index.html, not the streamProcessors ones.
  assertEquals(d.pluginLibs.map((l) => l.jsClassName).sort(), [
    "code_data_acme_RestRequest",
    "code_data_example_Filter",
    "flowSgiModules",
  ]);
});

Deno.test("fetches index.html and two json files, without a token", async () => {
  const server = new FakeServer();
  const seen: Record<string, string>[] = [];
  const fetch = server.fetch;
  const client = createClient({
    serverUrl: SERVER_URL,
    token: "",
    fetch: (url, init) => {
      seen.push(init.headers);
      return fetch(url, init);
    },
  });
  const result = await fetchDocs(client);
  assertEquals(result.version, "1.2.3");
  assertEquals(server.calls.map((c) => c.path).sort(), [
    "/static/docs/index.html",
    "/static/docs/json/classes.js",
    "/static/docs/json/symbols.js",
  ]);
  assertEquals(seen.every((h) => !("flow-token" in h)), true);
});

Deno.test("parameters: named ones are optional, and extra arguments are always allowed", () => {
  assertEquals(paramList({ args: ["msg"] }), "msg?: any, ...more: any[]");
  assertEquals(paramList({ args: [] }), "...more: any[]");
  assertEquals(
    paramList({ body: "function(html,policy){...}" }),
    "html?: any, policy?: any, ...more: any[]",
  );
  assertEquals(
    paramList({ body: "function(default, a, a, more){...}" }),
    "_default?: any, a?: any, a_?: any, more?: any, ...more_: any[]",
  );
  assertEquals(
    paramList({ body: "return ListHelper.toList(items);" }),
    "...args: any[]",
  );
});

Deno.test("hints become plain text for hover docs", () => {
  assertEquals(
    hintText("Wraps a value in an <code>Option</code> &amp; returns it.<br>See <a href='x'>docs</a>."),
    "Wraps a value in an `Option` & returns it.\nSee docs.",
  );
});

Deno.test("emits globals, object members with overloads, classes with aliases, and plugin classes", () => {
  const { text, skipped, pluginGlobals } = emitDeclarations(docs());
  assertStringIncludes(
    text,
    "// Generated by pathisync from https://flow.test/static/docs (docs version 1.2.3).",
  );
  assertStringIncludes(text, "declare function fromJValue(jv?: any, ...more: any[]): any;");
  assertStringIncludes(text, "declare var PayloadHelper: {");
  assertStringIncludes(text, "  trace(msg?: any, optionOfPayload?: any, ...more: any[]): any;");
  assertStringIncludes(text, "declare var HtmlHelper: {");
  assertStringIncludes(text, "  sanitize(html?: any, policy?: any, ...more: any[]): any;");
  assertStringIncludes(text, "  [key: string]: any;\n};");
  assertStringIncludes(
    text,
    "declare class code_data_SimpleData { constructor(...args: any[]); [key: string]: any; static [key: string]: any; }",
  );
  for (
    const name of [
      "ApiRequest",
      "generic_ApiRequest",
      "code_data_generic_ApiRequest",
      "code_model_flows_processors_queues_QueueMessageResponse",
      "code_data_acme_RestRequest",
    ]
  ) assertStringIncludes(text, `declare class ${name} {`);
  assertStringIncludes(
    text,
    "/** `code.data.acme.RestRequest` Constructs a code.data.acme.RestRequest, provided by a FlowSGI module that is loaded on first use. @see https://flow.test/static/docs/jsLibs/",
  );
  assertStringIncludes(text, "declare var flowSgiModules: any;");
  assertEquals(pluginGlobals, 3);
  // Members of objects aren't globals; `await` can't be declared.
  assertEquals(text.includes("declare function sanitize"), false);
  assertEquals(skipped, ["await"]);
});

Deno.test("output is identical whatever order the docs list things in", () => {
  const d = docs();
  const reversed = {
    ...d,
    symbols: [...d.symbols].reverse(),
    classes: [...d.classes].reverse(),
    pluginLibs: [...d.pluginLibs].reverse(),
  };
  assertEquals(emitDeclarations(reversed).text, emitDeclarations(d).text);
});

Deno.test("the output type-checks, and flags a misspelled global in flow code", () => {
  const dir = Deno.makeTempDirSync();
  Deno.mkdirSync(join(dir, "types"));
  Deno.mkdirSync(join(dir, "flows"));
  Deno.writeTextFileSync(join(dir, "types/pathify.d.ts"), emitDeclarations(docs()).text);
  Deno.writeTextFileSync(join(dir, "types/globals.d.ts"), globalsDts);
  Deno.writeTextFileSync(join(dir, "flows/jsconfig.json"), jsconfig);
  Deno.writeTextFileSync(
    join(dir, "flows/processors.js"),
    [
      "export function a_jsFunc() {",
      "  var obj = fromJValue(item.response().value());",
      "  PayloadHelper.trace('x', payload.get('y'), HtmlHelper.sanitize('<b>'), 1, 2, 3);",
      "  PayloadHelper.undocumented();",
      "  var bytes = JSON.stringify(obj).getBytes();",
      "  var JavaString = Java.type('java.lang.String');",
      "  new generic_ApiRequest('u', 'GET');",
      "  new code_data_acme_RestRequest('/path', 'GET');",
      "  return [new code_data_SimpleData(_.clone(obj)), fromJValeu(obj)];",
      "}",
      "",
    ].join("\n"),
  );
  const config = ts.getParsedCommandLineOfConfigFile(
    join(dir, "flows/jsconfig.json"),
    {},
    { ...ts.sys, onUnRecoverableConfigFileDiagnostic: () => {} },
  )!;
  const program = ts.createProgram(config.fileNames, config.options);
  const errors = ts.getPreEmitDiagnostics(program).map((d) =>
    `${d.file?.fileName.split("/").pop()}: ${
      ts.flattenDiagnosticMessageText(d.messageText, "\n")
    }`
  );
  assertEquals(errors, [
    "processors.js: Cannot find name 'fromJValeu'. Did you mean 'fromJValue'?",
  ]);
});
